language: ruby

before_install:
  - travis_retry gem install bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

env:
  - RAILS=master DB=sqlite3
  - RAILS=master DB=mysql
  - RAILS=master DB=postgres

before_script:
  - mysql -e 'create database ransack collate utf8_general_ci;'
  - mysql -e 'use ransack;show variables like "%character%";show variables like "%collation%";'
  - psql -c 'create database ransack;' -U postgres
