rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  - RAILS=v4.1.0.beta1 DB=sqlite3
  - RAILS=v4.1.0.beta1 DB=mysql
  - RAILS=v4.1.0.beta1 DB=postgres


before_script:
  - mysql -e 'create database ransack collate utf8_general_ci;'
  - mysql -e 'use ransack;show variables like "%character%";show variables like "%collation%";'
  - psql -c 'create database ransack;' -U postgres
