services: mongodb

language: ruby

sudo: false

rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9

env:
  - RAILS=master DB=mongodb
  - RAILS=master DB=sqlite3
  - RAILS=master DB=mysql
  - RAILS=master DB=postgres

  - RAILS=4-2-stable DB=mongodb
  - RAILS=4-2-stable DB=sqlite3
  - RAILS=4-2-stable DB=mysql
  - RAILS=4-2-stable DB=postgres

  - RAILS=4-1-stable DB=mongodb
  - RAILS=4-1-stable DB=sqlite3
  - RAILS=4-1-stable DB=mysql
  - RAILS=4-1-stable DB=postgres

  - RAILS=4-0-stable DB=sqlite3
  - RAILS=4-0-stable DB=mysql
  - RAILS=4-0-stable DB=postgres

  - RAILS=3-2-stable DB=sqlite
  - RAILS=3-2-stable DB=mysql
  - RAILS=3-2-stable DB=postgres

  - RAILS=3-1-stable DB=sqlite
  - RAILS=3-1-stable DB=mysql
  - RAILS=3-1-stable DB=postgres

  - RAILS=3-0-stable DB=sqlite
  - RAILS=3-0-stable DB=mysql
  - RAILS=3-0-stable DB=postgres

matrix:
  exclude:
    - rvm: 1.9
      env: RAILS=master
    - rvm: 2.0
      env: RAILS=master
  allow_failures:
    - env: RAILS=master DB=mongodb
    - env: RAILS=master DB=sqlite3
    - env: RAILS=master DB=mysql
    - env: RAILS=master DB=postgres
    - rvm: 2.2
      env: RAILS=3-2-stable
      env: RAILS=3-1-stable
      env: RAILS=3-0-stable

before_script:
  - mysql -e 'create database ransack collate utf8_general_ci;'
  - mysql -e 'use ransack;show variables like "%character%";show variables like "%collation%";'
  - psql -c 'create database ransack;' -U postgres
